/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuwang_jni_DataConvert */

#ifndef _Included_com_wuwang_jni_DataConvert
#define _Included_com_wuwang_jni_DataConvert
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wuwang_jni_DataConvert_RGBA_YUV420SP
#define com_wuwang_jni_DataConvert_RGBA_YUV420SP 16402L
#undef com_wuwang_jni_DataConvert_BGRA_YUV420SP
#define com_wuwang_jni_DataConvert_BGRA_YUV420SP 16912L
#undef com_wuwang_jni_DataConvert_RGBA_YUV420P
#define com_wuwang_jni_DataConvert_RGBA_YUV420P 81938L
#undef com_wuwang_jni_DataConvert_BGRA_YUV420P
#define com_wuwang_jni_DataConvert_BGRA_YUV420P 82448L
#undef com_wuwang_jni_DataConvert_RGB_YUV420SP
#define com_wuwang_jni_DataConvert_RGB_YUV420SP 12306L
#undef com_wuwang_jni_DataConvert_RGB_YUV420P
#define com_wuwang_jni_DataConvert_RGB_YUV420P 77842L
#undef com_wuwang_jni_DataConvert_BGR_YUV420SP
#define com_wuwang_jni_DataConvert_BGR_YUV420SP 12816L
#undef com_wuwang_jni_DataConvert_BGR_YUV420P
#define com_wuwang_jni_DataConvert_BGR_YUV420P 78352L
/*
 * Class:     com_wuwang_jni_DataConvert
 * Method:    rgbaToYuv
 * Signature: ([BII[BI)V
 */
JNIEXPORT void JNICALL Java_com_wuwang_jni_DataConvert_rgbaToYuv
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
